incorporate errors into message, put details into details

diff --git a/.github/build.in.yml b/.github/build.in.yml
--- a/.github/build.in.yml
+++ b/.github/build.in.yml
@@ -614,7 +614,18 @@ jobs:
           echo "$TITLE"
           label_names=$(echo "${{ toJson(github.event.pull_request.labels) }}" | jq -r '.[].name')
           echo "$label_names"
-          lake exe check-title-labels --labels "$label_names" "$TITLE"
+
+          # Capture output and exit code
+          if output=$(lake exe check-title-labels --labels "$label_names" "$TITLE" 2>&1); then
+            echo "Check passed"
+          else
+            exit_code="$?"
+            # Escape and set the output for use in subsequent steps
+            echo "errors<<EOF" >> "$GITHUB_OUTPUT"
+            echo "$output" >> "$GITHUB_OUTPUT"
+            echo "EOF" >> "$GITHUB_OUTPUT"
+            exit "$exit_code"
+          fi
 
       - name: Add comment to fix PR title
         uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
@@ -625,11 +636,16 @@ jobs:
             ### 🚨 PR Title Needs Formatting
             Please update the title to match our [commit style conventions](https://leanprover-community.github.io/contribute/commit.html).
 
+            Errors from script:
+            ${{ steps.pr-title-check.outputs.message }}
+
+            <details>
+            <summary>Details on the required title format</summary>
+
             The title should fit the following format:
             ```
             <type>(<optional-scope>): <subject>
             ```
-
             `<type>` is:
 
             - `feat` (feature)
@@ -640,6 +656,7 @@ jobs:
             - `test` (when adding missing tests)
             - `chore` (maintain)
             - `perf` (performance improvement, optimization, ...)
+            - `ci` (changes to continuous integration, repo automation, ...)
 
             `<optional-scope>` is a name of module or a directory which contains changed modules.
             This is not necessary to include, but may be useful if the `<subject>` is insufficient.
@@ -655,6 +672,7 @@ jobs:
             - use imperative, present tense: "change" not "changed" nor "changes"
             - do not capitalize the first letter
             - no dot(.) at the end
+            </details>
 
       - name: Add comment that PR title is fixed
         if: ${{ steps.pr-title-check.outputs.success == 'true'}}
