feat(CI): use `mk_all` twice (#14077)
Once to create the import all files without failing, the second time actually checking.

[Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/PR.20fail.3A.20Error.3A.20Process.20completed.20with.20exit.20code.201.2E/near/446419185)

diff --git a/.github/build.in.yml b/.github/build.in.yml
--- a/.github/build.in.yml
+++ b/.github/build.in.yml
@@ -130,9 +130,6 @@ jobs:
           lean --version
           lake --version
 
-      - name: check {Mathlib, Tactic, Counterexamples, Archive}.lean are up to date
-        run: lake exe mk_all --check
-
       - name: build cache
         run: |
           lake build cache
@@ -160,7 +157,7 @@ jobs:
         with:
           linters: gcc
           run: |
-            bash -o pipefail -c "env LEAN_ABORT_ON_PANIC=1 lake build --wfail -KCI"
+            bash -o pipefail -c "lake exe mk_all || echo "There are unaccounted for files, but I am not failing yet!"; env LEAN_ABORT_ON_PANIC=1 lake build --wfail -KCI"
 
       - name: upload cache
         # We only upload the cache if the build started (whether succeeding, failing, or cancelled)
@@ -215,6 +212,9 @@ jobs:
         env:
           MATHLIB_CACHE_SAS: ${{ secrets.MATHLIB_CACHE_SAS }}
           MATHLIB_CACHE_S3_TOKEN: ${{ secrets.MATHLIB_CACHE_S3_TOKEN }}
+
+      - name: update {Mathlib, Tactic, Counterexamples, Archive}.lean
+        run: lake exe mk_all --check
 
       - name: check for noisy stdout lines
         id: noisy
