feat(CI): manage `merge-conflict` label on push

diff --git a/.github/build.in.yml b/.github/build.in.yml
--- a/.github/build.in.yml
+++ b/.github/build.in.yml
@@ -32,6 +32,26 @@ jobs:
 
       - uses: actions/checkout@v4
 
+      - name: Update the merge-conflict label
+        run: |
+          if git merge origin/master --no-ff --no-commit
+          then
+            git merge --abort || true
+            echo "This PR does not have merge conflicts with master."
+            # we use curl rather than octokit/request-action so that the job won't fail
+            # (and send an annoying email) if the labels don't exist
+            curl --request DELETE \
+              --url https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.PR.outputs.number }}/labels/merge-conflict \
+              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
+          else
+            echo "This PR has merge conflicts with main."
+            # we use curl rather than octokit/request-action so that the job won't fail
+            # (and send an annoying email) if the labels don't exist
+            curl --request POST \
+              --url https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.PR.outputs.number }}/labels/merge-conflict \
+              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
+          fi
+
       # Run the case checker action
       - name: Check Case Sensitivity
         uses: credfeto/action-case-checker@v1.3.0
