printf debugging

diff --git a/.github/workflows/nightly-regression-report.yml b/.github/workflows/nightly-regression-report.yml
--- a/.github/workflows/nightly-regression-report.yml
+++ b/.github/workflows/nightly-regression-report.yml
@@ -68,22 +68,27 @@ jobs:
         # Use a temporary file to ensure we don't overflow max variable size.
         lean_outfile=$(mktemp)
         # Show the stdout in the GitHub build logs, while we process it from the file.
-        lake build | tee "${lean_outfile}"
+        lake build | tee "${lean_outfile}" || true
 
         # Skip the lines about build progress.
         filtered_out=$(grep -v '^✔' "${lean_outfile}" | grep -v '^trace: ')
+        echo "$(wc -l <<<"${filtered_out}") lines of output"
 
         # Categorize the output.
         error_lines=$(grep '^error: ' <<<"${filtered_out}")
         error_descriptions=$(sed 's/^error: [^:]*:[0-9]*:[0-9]*: //' <<<"${error_lines}")
+        echo "$(wc -l <<<"${error_lines}") lines of errors"
         warning_lines=$(grep '^warning: ' <<<"${filtered_out}")
         warning_descriptions=$(sed 's/^warning: [^:]*:[0-9]*:[0-9]*: //' <<<"${warning_lines}")
+        echo "$(wc -l <<<"${warning_lines}") lines of warnings"
         # Panics are reported as an info message.
         # They should be very prominent when debugging, so treat them differently.
         panic_lines=$(grep '^info: .*PANIC at ' <<<"${filtered_out}")
         panic_descriptions=$(sed 's/^info: [^:]*:[0-9]*:[0-9]*: //' <<<"${panic_lines}")
+        echo "$(wc -l <<<"${panic_lines}") lines of panic"
         info_lines=$(grep '^info: ' <<<"${filtered_out}" | grep -v 'PANIC at ')
         info_descriptions=$(sed 's/^info: [^:]*:[0-9]*:[0-9]*: //' <<<"${info_lines}")
+        echo "$(wc -l <<<"${info_lines}") lines of info"
 
         # Some additional postprocessing for specific forms of messages.
         # Remove the extra arguments to linarith, to count them correctly.
@@ -91,6 +96,8 @@ jobs:
         warning_descriptions=$(sed "s/'linarith \[.*\]'/'linarith'/" <<<"${warning_descriptions}")
         # Deal with line wrapping ending the argument list to `linarith` too early.
         warning_descriptions=$(sed "s/'linarith \[[^]]*$/'linarith' succeeded. Counterexample:/" <<<"${warning_descriptions}")
+
+        echo "generating Zulip message..."
 
         delimiter=$(cat /proc/sys/kernel/random/uuid)
         echo "zulip-message<<${delimiter}" >> "$GITHUB_OUTPUT"
