chore: automate nightly-testing-YYYY-MM-DD branches

diff --git a/.github/workflows/nightly_bump_toolchain.yml b/.github/workflows/nightly_bump_toolchain.yml
--- a/.github/workflows/nightly_bump_toolchain.yml
+++ b/.github/workflows/nightly_bump_toolchain.yml
@@ -32,3 +32,12 @@ jobs:
         git add lean-toolchain
         git commit -m "chore: bump to ${RELEASE_TAG}"
         git push origin nightly-testing
+        # Now create/update the `nightly-testing-YYYY-MM-DD` branch:
+        toolchain=$(<lean-toolchain)
+        if [[ $toolchain =~ leanprover/lean4:nightly-([a-zA-Z0-9_-]+) ]]; then
+          version=${BASH_REMATCH[1]}
+          git push origin refs/heads/nightly-testing:refs/heads/nightly-testing-$version
+        else
+          echo "Error: The file lean-toolchain does not contain the expected pattern."
+          exit 1
+        fi
